import { useState, useEffect, useRef } from 'react';
import { Layers, Calendar, Sparkles, Loader2, RefreshCw } from 'lucide-react';
import EditorControls from './EditorControls';
import SlideCanvas from './SlideCanvas';
import SlideNavigator from './SlideNavigator';
import { SermonAnalysisData, CardNewsSlide } from '../../utils/mockData';
import { generateCardNewsFromSermon } from '../../api/client';

interface CardNewsTabProps {
  sermonData: SermonAnalysisData;
  setSermonData: (data: SermonAnalysisData) => void;
  targetSubTab?: 'full_sermon' | 'daily';
  targetDay?: string;
}

export default function CardNewsTab({
  sermonData,
  setSermonData,
  targetSubTab = 'full_sermon',
  targetDay = '1',
}: CardNewsTabProps) {
  const canvasRef = useRef<HTMLDivElement | null>(null);

  // 'full_sermon' (설교카드 7장) | 'daily' (5day 묵상카드)
  const [subTab, setSubTab] = useState<'full_sermon' | 'daily'>(targetSubTab);
  const [selectedDailyDay, setSelectedDailyDay] = useState(targetDay);
  const [isGenerating, setIsGenerating] = useState(false);

  // Check if cards have been generated by user action
  const hasCards = Boolean(
    (sermonData.sermonCardNews && sermonData.sermonCardNews.length > 0) ||
    (sermonData.dailyCardNewsSets && Object.keys(sermonData.dailyCardNewsSets).length > 0)
  );

  useEffect(() => {
    if (targetSubTab) setSubTab(targetSubTab);
    if (targetDay) setSelectedDailyDay(targetDay);
  }, [targetSubTab, targetDay]);

  // 에디터 스타일 상태
  const [bgTheme, setBgTheme] = useState('navy');
  const [customBgUrl, setCustomBgUrl] = useState<string | null>(null);
  const [fontFamily, setFontFamily] = useState<'serif' | 'sans'>('serif');
  const [fontSize, setFontSize] = useState<'sm' | 'md' | 'lg'>('md');
  const [aspectRatio, setAspectRatio] = useState<'4:5' | '9:16'>('4:5');
  const [churchName, setChurchName] = useState(sermonData.metadata?.churchName || '예배공동체');

  const [currentIndex, setCurrentIndex] = useState(0);

  const isFullSermon = subTab === 'full_sermon';

  // 사용자가 '설교카드 생성' 버튼을 눌렀을 때만 생성 실행
  const handleGenerateCards = async () => {
    setIsGenerating(true);
    try {
      const generated = await generateCardNewsFromSermon(sermonData);
      setSermonData({
        ...sermonData,
        sermonCardNews: generated.sermonCardNews,
        dailyCardNewsSets: generated.dailyCardNewsSets,
      });
      setCurrentIndex(0);
    } catch (e) {
      console.error(e);
    } finally {
      setIsGenerating(false);
    }
  };

  const getFallbackSlides = (): CardNewsSlide[] => {
    const meta = sermonData.metadata || {};
    const title = meta.title || '은혜로운 주일 설교 말씀';
    const passage = meta.passage || '성경 본문';
    const preacher = meta.preacher || '담임목사';
    const church = churchName || meta.churchName || '예배공동체';

    if (isFullSermon) {
      const cards: CardNewsSlide[] = [
        {
          id: 1,
          type: 'cover',
          tag: '주일 설교 요약',
          title: title,
          subtitle: sermonData.shorts?.[0]?.summary || '말씀 속에서 발견하는 하나님의 은혜와 진리',
          passage: passage,
          speaker: preacher,
          church: church,
        }
      ];

      for (let i = 0; i < 5; i++) {
        const sh = sermonData.shorts?.[i];
        const med = sermonData.meditations?.[i];
        const pointTitle = sh?.title_answer || med?.theme || `믿음의 핵심 원리 0${i + 1}`;
        const pointBody = sh?.summary || (med?.content ? med.content.slice(0, 140) : '하나님을 바라보고 믿음의 자리를 굳게 지키십시오.');

        cards.push({
          id: i + 2,
          type: 'content',
          tag: `Point 0${i + 1}`,
          title: pointTitle,
          body: pointBody,
        });
      }

      cards.push({
        id: 7,
        type: 'closing',
        tag: '결단과 기도',
        title: '오늘의 믿음 결단',
        body: `"${title} 말씀을 마음에 새기고,\n세상 속에서 빛과 소금의 삶을 살아가게 하옵소서.\n예수 그리스도의 이름으로 기도드립니다. 아멘."`,
        church: church,
      });

      return cards;
    } else {
      const dayIdx = parseInt(selectedDailyDay, 10) - 1;
      const dayNames = ['월', '화', '수', '목', '금'];
      const currentDayName = dayNames[dayIdx] || '월';
      const med = sermonData.meditations?.[dayIdx];

      const theme = med?.theme || `${title} - Day ${selectedDailyDay} 묵상`;
      const verse = med?.bibleVerse ? med.bibleVerse.split('\n')[0] : passage;
      const content = med?.content || '오늘 주신 말씀을 깊이 묵상하며 주님의 음성에 귀 기울입니다.';
      const question = med?.question || '오늘 나에게 주신 말씀은 무엇입니까?';
      const application = med?.application || '말씀을 기억하며 오늘 하루 믿음으로 순종하기.';
      const prayer = med?.closingPrayer || '주님과 동행하는 복된 하루가 되게 하옵소서. 아멘.';

      return [
        {
          id: 1,
          type: 'cover',
          tag: `Day ${selectedDailyDay} (${currentDayName})`,
          title: theme,
          passage: verse,
          church: church,
        },
        {
          id: 2,
          type: 'content',
          tag: '말씀 묵상',
          title: '말씀과 은혜',
          body: content.slice(0, 180) + (content.length > 180 ? '...' : ''),
        },
        {
          id: 3,
          type: 'content',
          tag: '삶의 적용',
          title: '일상의 실천',
          body: `질문: ${question}\n\n적용: ${application}`,
        },
        {
          id: 4,
          type: 'closing',
          tag: '마치는 기도',
          title: `${currentDayName}요일의 기도`,
          body: prayer,
          church: church,
        },
      ];
    }
  };

  const rawSlides = isFullSermon
    ? sermonData.sermonCardNews
    : sermonData.dailyCardNewsSets?.[selectedDailyDay];

  const slides = (rawSlides && Array.isArray(rawSlides) && rawSlides.length > 0)
    ? rawSlides
    : getFallbackSlides();

  const currentSlide = slides[currentIndex] || slides[0] || ({} as CardNewsSlide);

  const handleUpdateSlide = (slideIndex: number, updatedSlide: CardNewsSlide) => {
    if (isFullSermon) {
      const newSermonCards = [...slides];
      newSermonCards[slideIndex] = updatedSlide;
      setSermonData({ ...sermonData, sermonCardNews: newSermonCards });
    } else {
      const newDailySets = { ...(sermonData.dailyCardNewsSets || {}) };
      const currentDaySet = [...slides];
      currentDaySet[slideIndex] = updatedSlide;
      newDailySets[selectedDailyDay] = currentDaySet;
      setSermonData({ ...sermonData, dailyCardNewsSets: newDailySets });
    }
  };

  const handleSubTabChange = (tab: 'full_sermon' | 'daily') => {
    setSubTab(tab);
    setCurrentIndex(0);
  };

  const handleDayChange = (day: string) => {
    setSelectedDailyDay(day);
    setCurrentIndex(0);
  };

  // 🌟 아직 생성되지 않은 상태: '설교카드 생성' 버튼 화면만 노출
  if (!hasCards) {
    return (
      <div className="max-w-2xl mx-auto py-12 animate-fadeIn">
        <div className="bg-white rounded-3xl p-8 border border-[#EAE8E1] text-center space-y-5 shadow-xs">
          <div className="w-14 h-14 rounded-2xl bg-[#FAF9F5] border border-[#E0DED7] flex items-center justify-center mx-auto text-[#DA7756]">
            <Layers className="w-7 h-7" />
          </div>

          <div className="space-y-1">
            <h2 className="text-base font-bold text-[#282622]">설교카드 & 묵상카드 생성</h2>
            <p className="text-xs text-[#807D77] font-medium">
              {sermonData.metadata?.title || '설교 본문'} &bull; {sermonData.metadata?.passage || '성경 구절'}
            </p>
          </div>

          <button
            type="button"
            disabled={isGenerating}
            onClick={handleGenerateCards}
            className="w-full sm:w-auto px-6 py-3 rounded-xl bg-[#282622] hover:bg-[#1E1D1A] text-white text-xs font-bold transition-all inline-flex items-center justify-center gap-2 shadow-sm disabled:opacity-50"
          >
            {isGenerating ? (
              <>
                <Loader2 className="w-4 h-4 animate-spin text-[#DA7756]" />
                <span>설교카드 및 묵상카드 생성 중...</span>
              </>
            ) : (
              <>
                <Sparkles className="w-4 h-4 text-[#DA7756]" />
                <span>설교카드 생성</span>
              </>
            )}
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-5 max-w-4xl mx-auto">
      {/* 서브탭 헤더 */}
      <div className="bg-white rounded-2xl p-4 border border-[#EAE8E1] flex flex-col sm:flex-row items-center justify-between gap-3">
        <div className="flex items-center gap-1.5 p-1 bg-[#EFECE3] rounded-xl w-full sm:w-auto">
          <button
            onClick={() => handleSubTabChange('full_sermon')}
            className={`flex-1 sm:flex-none flex items-center justify-center gap-2 px-3.5 py-1.5 rounded-lg text-xs font-semibold transition-all ${
              isFullSermon
                ? 'bg-white text-[#282622] shadow-xs'
                : 'text-[#66635E] hover:text-[#282622]'
            }`}
          >
            <Layers className="w-3.5 h-3.5" />
            <span>설교카드 (7장)</span>
          </button>

          <button
            onClick={() => handleSubTabChange('daily')}
            className={`flex-1 sm:flex-none flex items-center justify-center gap-2 px-3.5 py-1.5 rounded-lg text-xs font-semibold transition-all ${
              !isFullSermon
                ? 'bg-white text-[#282622] shadow-xs'
                : 'text-[#66635E] hover:text-[#282622]'
            }`}
          >
            <Calendar className="w-3.5 h-3.5" />
            <span>5day 묵상카드 (월~금)</span>
          </button>
        </div>

        <div className="flex items-center gap-2">
          {!isFullSermon && (
            <div className="flex items-center gap-1 overflow-x-auto">
              {['1', '2', '3', '4', '5'].map((day) => {
                const dayNames: Record<string, string> = { '1': '월', '2': '화', '3': '수', '4': '목', '5': '금' };
                const isActive = selectedDailyDay === day;
                return (
                  <button
                    key={day}
                    onClick={() => handleDayChange(day)}
                    className={`px-2.5 py-1 rounded-lg text-xs font-semibold ${
                      isActive ? 'bg-[#282622] text-white' : 'bg-[#FAF9F5] text-[#66635E] border border-[#EAE8E1]'
                    }`}
                  >
                    Day {day} ({dayNames[day]})
                  </button>
                );
              })}
            </div>
          )}

          <button
            type="button"
            disabled={isGenerating}
            onClick={handleGenerateCards}
            className="flex items-center gap-1 px-3 py-1.5 rounded-xl border border-[#E0DED7] text-xs font-medium text-[#66635E] hover:bg-[#FAF9F5] transition-colors"
          >
            {isGenerating ? <Loader2 className="w-3 h-3 animate-spin" /> : <RefreshCw className="w-3 h-3" />}
            <span>재생성</span>
          </button>
        </div>
      </div>

      {/* 스타일 컨트롤바 */}
      <EditorControls
        bgTheme={bgTheme}
        setBgTheme={setBgTheme}
        customBgUrl={customBgUrl}
        setCustomBgUrl={setCustomBgUrl}
        fontFamily={fontFamily}
        setFontFamily={setFontFamily}
        fontSize={fontSize}
        setFontSize={setFontSize}
        aspectRatio={aspectRatio}
        setAspectRatio={setAspectRatio}
        churchName={churchName}
        setChurchName={setChurchName}
      />

      {/* 슬라이드 캔버스 프리뷰 */}
      <SlideCanvas
        slide={currentSlide}
        index={currentIndex}
        total={slides.length}
        bgTheme={bgTheme}
        customBgUrl={customBgUrl}
        fontFamily={fontFamily}
        fontSize={fontSize}
        aspectRatio={aspectRatio}
        churchName={churchName}
        onUpdateSlide={handleUpdateSlide}
        canvasRef={canvasRef}
      />

      {/* 네비게이터 & 다운로드 */}
      <SlideNavigator
        slides={slides}
        currentIndex={currentIndex}
        setCurrentIndex={setCurrentIndex}
        canvasRef={canvasRef}
        title={isFullSermon ? 'sermon-full' : `sermon-day${selectedDailyDay}`}
      />
    </div>
  );
}
